name: hpcnas
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - cffi>=1.11.0
  - Pillow
  - pybind11
  - rust
  - cmake-build-extension
  - jq
  - libgcc-ng=12
  - libstdcxx-ng=12
  - pip
  - pip:
    - qualname>=0.1.0
    - keras_preprocessing>=1.1.2
    - numpy>=1.16.0
    - requests
